image: node:22

stages:
  - test

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm run build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
