import { useState, useCallback } from 'react';
import { FilePlus, Plus, Trash2, CheckCircle, FileText, AlertTriangle } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { cn } from '@/lib/utils';
import { useCreateWasteRecord } from '@/features/waste/api/use-create-waste-record';
import { CATEGORIES, CATEGORY_LABELS } from '@/features/waste/constants';
import { Input } from '@/components/ui/input';
import {
  DialogRoot,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import type { WasteCategory } from '@/features/waste/types';

type FormEntry = {
  category: WasteCategory;
  quantity: string;
  unit: string;
  reportedAt: string;
  notes: string;
};

type ToastState = {
  show: boolean;
  message: string;
  entries: FormEntry[];
  fileName: string;
};

const downloadPdfReport = (entries: FormEntry[], fileName: string) => {
  const doc = new jsPDF();
  const margin = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('WASTE REPORTING SUBMISSION REPORT', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Date: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`,
    margin,
    y,
  );
  y += 6;
  doc.text(
    `Time: ${new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`,
    margin,
    y,
  );
  y += 6;
  doc.text(`Total Records: ${entries.length}`, margin, y);
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  const cols = [
    { x: margin, label: '#' },
    { x: margin + 10, label: 'Category' },
    { x: margin + 60, label: 'Quantity' },
    { x: margin + 95, label: 'Date' },
    { x: margin + 125, label: 'Remarks' },
  ];
  cols.forEach((col) => doc.text(col.label, col.x, y));
  y += 5;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 4;

  doc.setFont('helvetica', 'normal');
  entries.forEach((entry, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    const catLabel = CATEGORY_LABELS[entry.category] ?? entry.category;
    doc.text(`${i + 1}`, margin, y);
    doc.text(catLabel, margin + 10, y);
    doc.text(`${entry.quantity} ${entry.unit}`, margin + 60, y);
    doc.text(entry.reportedAt, margin + 95, y);
    doc.text(entry.notes || '(none)', margin + 125, y);
    y += 6;
  });

  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.text('Generated by Migsel Inspector Portal', pageWidth / 2, y, { align: 'center' });

  doc.save(fileName);
};

export const WasteReportingForm = () => {
  const createRecord = useCreateWasteRecord();

  const [form, setForm] = useState({
    category: '' as WasteCategory | '',
    quantity: '',
    unit: '',
    reportedAt: '',
    notes: '',
  });

  const [entries, setEntries] = useState<FormEntry[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);

  const [toast, setToast] = useState<ToastState>({
    show: false,
    message: '',
    entries: [],
    fileName: '',
  });

  const resetForm = useCallback(() => {
    setForm({ category: '', quantity: '', unit: '', reportedAt: '', notes: '' });
  }, []);

  const getMissingFields = () => {
    const missing: string[] = [];
    if (!form.category) missing.push('Category');
    if (!form.quantity) missing.push('Quantity');
    if (!form.unit) missing.push('Unit');
    if (!form.reportedAt) missing.push('Date');
    return missing;
  };

  const handleAdd = () => {
    const missing = getMissingFields();
    if (missing.length > 0) {
      alert(`Please fill in the following required fields:\n- ${missing.join('\n- ')}`);
      return;
    }

    setEntries((prev) => [
      ...prev,
      {
        category: form.category as WasteCategory,
        quantity: form.quantity,
        unit: form.unit,
        reportedAt: form.reportedAt,
        notes: form.notes,
      },
    ]);
    resetForm();
  };

  const handleRemoveEntry = (index: number) => {
    setEntries((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSubmitAll = () => {
    if (entries.length === 0) {
      alert('No entries to submit. Add at least one record first.');
      return;
    }
    setConfirmOpen(true);
  };

  const executeSubmit = async () => {
    setConfirmOpen(false);
    setSubmitting(true);

    try {
      for (const entry of entries) {
        await new Promise<void>((resolve, reject) => {
          createRecord.mutate(
            {
              category: entry.category,
              quantity: Number(entry.quantity),
              unit: entry.unit,
              reportedAt: entry.reportedAt,
              notes: entry.notes,
            },
            {
              onSuccess: () => resolve(),
              onError: (err) => reject(err),
            },
          );
        });
      }

      const fileName = `waste-report-batch-${Date.now()}.pdf`;

      setToast({
        show: true,
        message: `${entries.length} waste record${entries.length > 1 ? 's' : ''} submitted successfully!`,
        entries: [...entries],
        fileName,
      });
      setEntries([]);
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to submit waste records');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDownload = () => {
    downloadPdfReport(toast.entries, toast.fileName);
    setToast((prev) => ({ ...prev, show: false }));
  };

  const dismissToast = () => {
    setToast((prev) => ({ ...prev, show: false }));
  };

  return (
    <>
      <div className="animate-in fade-in-0 slide-in-from-bottom-2 duration-500 [animation-delay:200ms]">
        <div className="rounded-xl border border-white/20 bg-white/60 p-4 shadow-xs backdrop-blur-sm sm:p-6">
          <div className="mb-4 flex items-center gap-3 border-b border-slate-200/60 pb-3 sm:mb-6 sm:pb-4">
            <div className="bg-primary/10 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg sm:h-9 sm:w-9">
              <FilePlus className="text-primary h-3.5 w-3.5 sm:h-4 sm:w-4" />
            </div>
            <div className="min-w-0">
              <h2 className="text-foreground text-sm font-semibold sm:text-base">
                New Waste Record
              </h2>
              <p className="text-muted-foreground truncate text-xs">
                Fill in the details to submit a new waste record
              </p>
            </div>
          </div>

          <div className="space-y-4 sm:space-y-5">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleAdd();
              }}
              className="space-y-3 sm:space-y-5"
            >
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-5">
                <div className="space-y-1.5">
                  <label className="text-foreground text-xs font-semibold tracking-wide">
                    Category
                  </label>
                  <select
                    value={form.category}
                    onChange={(e) =>
                      setForm({ ...form, category: e.target.value as WasteCategory })
                    }
                    className="border-input bg-background text-foreground focus-visible:border-ring focus-visible:ring-ring/30 flex h-11 w-full items-center rounded-lg border px-3 text-sm transition-all outline-none focus-visible:ring-2 sm:h-10"
                  >
                    <option value="" disabled>
                      Select a category
                    </option>
                    {CATEGORIES.map((c) => (
                      <option key={c.value} value={c.value}>
                        {c.label}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-foreground text-xs font-semibold tracking-wide">
                    Quantity
                  </label>
                  <div className="flex gap-2">
                    <div className="flex-1">
                      <Input
                        type="number"
                        step="0.1"
                        min="0"
                        value={form.quantity}
                        onChange={(e) => setForm({ ...form, quantity: e.target.value })}
                        placeholder="0.0"
                        required
                      />
                    </div>
                    <div className="w-24">
                      <select
                        value={form.unit}
                        onChange={(e) => setForm({ ...form, unit: e.target.value })}
                        className="border-input bg-background text-foreground focus-visible:border-ring focus-visible:ring-ring/30 flex h-11 w-full items-center rounded-lg border px-2 text-sm transition-all outline-none focus-visible:ring-2 sm:h-10"
                      >
                        <option value="" disabled>
                          Unit
                        </option>
                        <option value="kg">kg</option>
                        <option value="ton">ton</option>
                        <option value="liter">liter</option>
                        <option value="cubic meter">m³</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-foreground text-xs font-semibold tracking-wide">
                    Date
                  </label>
                  <Input
                    type="date"
                    value={form.reportedAt}
                    onChange={(e) => setForm({ ...form, reportedAt: e.target.value })}
                    max={new Date().toISOString().split('T')[0]}
                    required
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-foreground text-xs font-semibold tracking-wide">
                    Remarks
                  </label>
                  <textarea
                    value={form.notes}
                    onChange={(e) => setForm({ ...form, notes: e.target.value })}
                    placeholder="Additional details..."
                    className="border-input bg-background text-foreground placeholder:text-muted-foreground/50 focus-visible:border-ring focus-visible:ring-ring/30 min-h-[96px] w-full rounded-lg border px-3 py-2.5 text-sm transition-all outline-none focus-visible:ring-2 sm:min-h-[80px] sm:py-2"
                  />
                </div>
              </div>

              <div className="flex flex-col-reverse gap-2 border-t border-slate-200/60 pt-4 sm:flex-row sm:items-center sm:justify-end sm:gap-3 sm:pt-5">
                <button
                  type="button"
                  onClick={resetForm}
                  className="text-muted-foreground hover:text-foreground rounded-lg px-4 py-3 text-sm font-medium transition-all sm:py-2"
                >
                  Clear
                </button>
                <button
                  type="submit"
                  className="bg-primary hover:bg-primary/90 text-primary-foreground inline-flex items-center justify-center gap-2 rounded-lg px-6 py-3 text-sm font-semibold shadow-xs transition-all hover:shadow-md active:scale-95 sm:py-2.5"
                >
                  <Plus className="h-4 w-4" />
                  Add
                </button>
              </div>
            </form>

            {entries.length > 0 && (
              <div className="border-t border-slate-200/60 pt-4 sm:pt-5">
                <div className="mb-2 flex items-center justify-between sm:mb-3">
                  <h3 className="text-foreground text-sm font-semibold">
                    Pending Entries ({entries.length})
                  </h3>
                </div>
                <div className="max-h-48 overflow-x-auto rounded-lg border border-slate-200/60 sm:max-h-64">
                  <table className="hidden w-full min-w-[500px] text-left text-xs sm:table">
                    <thead className="sticky top-0 bg-slate-50/80">
                      <tr>
                        <th className="px-3 py-2 font-semibold text-slate-500">#</th>
                        <th className="px-3 py-2 font-semibold text-slate-500">Category</th>
                        <th className="px-3 py-2 font-semibold text-slate-500">Quantity</th>
                        <th className="px-3 py-2 font-semibold text-slate-500">Date</th>
                        <th className="px-3 py-2 font-semibold text-slate-500">Remarks</th>
                        <th className="px-3 py-2 font-semibold text-slate-500"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {entries.map((entry, i) => (
                        <tr key={i} className="hover:bg-slate-50/50">
                          <td className="text-muted-foreground px-3 py-2">{i + 1}</td>
                          <td className="px-3 py-2 font-medium">
                            {CATEGORY_LABELS[entry.category] ?? entry.category}
                          </td>
                          <td className="px-3 py-2">
                            {entry.quantity} {entry.unit}
                          </td>
                          <td className="px-3 py-2">{entry.reportedAt}</td>
                          <td className="text-muted-foreground max-w-[160px] truncate px-3 py-2">
                            {entry.notes || '\u2014'}
                          </td>
                          <td className="px-3 py-2">
                            <button
                              type="button"
                              onClick={() => handleRemoveEntry(i)}
                              className="text-muted-foreground hover:text-destructive rounded p-1 transition-all"
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  <div className="divide-y divide-slate-100 sm:hidden">
                    {entries.map((entry, i) => (
                      <div key={i} className="flex items-start gap-2 px-3 py-3">
                        <div className="flex min-w-0 flex-1 flex-col gap-0.5">
                          <div className="flex items-center gap-2">
                            <span className="text-muted-foreground text-xs">{i + 1}.</span>
                            <span className="truncate text-sm font-medium">
                              {CATEGORY_LABELS[entry.category] ?? entry.category}
                            </span>
                          </div>
                          <div className="text-muted-foreground flex flex-wrap gap-x-3 gap-y-0.5 text-xs">
                            <span>
                              {entry.quantity} {entry.unit}
                            </span>
                            <span>{entry.reportedAt}</span>
                            {entry.notes && (
                              <span className="max-w-[140px] truncate">{entry.notes}</span>
                            )}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => handleRemoveEntry(i)}
                          className="text-muted-foreground hover:text-destructive mt-0.5 shrink-0 rounded p-1.5 transition-all"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-4 flex flex-col-reverse items-stretch gap-2 sm:flex-row sm:items-center sm:justify-end sm:gap-3">
                  <button
                    type="button"
                    onClick={() => setEntries([])}
                    className="text-muted-foreground hover:text-foreground rounded-lg px-4 py-2 text-sm font-medium transition-all"
                  >
                    Clear All
                  </button>
                  <button
                    type="button"
                    onClick={handleSubmitAll}
                    disabled={submitting}
                    className={cn(
                      'inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-6 py-2.5 text-sm font-semibold text-white shadow-xs transition-all hover:bg-emerald-700 hover:shadow-md active:scale-95 disabled:pointer-events-none disabled:opacity-50',
                    )}
                  >
                    {submitting ? (
                      <>
                        <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
                        Submitting...
                      </>
                    ) : (
                      <>
                        <CheckCircle className="h-4 w-4" />
                        Submit All
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <DialogRoot open={confirmOpen} onOpenChange={setConfirmOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Confirm Submission</DialogTitle>
            <DialogDescription>
              You are about to submit {entries.length} waste record{entries.length !== 1 ? 's' : ''}{' '}
              to the system. This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <div className="flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50/50 p-3 text-sm">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
            <p className="text-amber-800">
              Please verify all entries are correct before proceeding.
            </p>
          </div>
          <DialogFooter>
            <button
              type="button"
              onClick={() => setConfirmOpen(false)}
              className="text-muted-foreground hover:text-foreground rounded-lg px-4 py-2 text-sm font-medium transition-all"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={executeSubmit}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-6 py-2 text-sm font-semibold text-white shadow-xs transition-all hover:bg-emerald-700 hover:shadow-md active:scale-95"
            >
              <CheckCircle className="h-4 w-4" />
              Yes, Submit
            </button>
          </DialogFooter>
        </DialogContent>
      </DialogRoot>

      {toast.show && (
        <div className="animate-in fade-in-0 fixed inset-0 z-50 flex items-center justify-center bg-black/30 duration-200">
          <div className="bg-card border-border shadow-elevated animate-in zoom-in-95 fade-in-0 mx-4 flex w-full max-w-sm items-start gap-3 rounded-xl border p-4 shadow-lg duration-200">
            <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-100">
              <CheckCircle className="h-4 w-4 text-emerald-600" />
            </div>
            <div className="flex-1">
              <p className="text-foreground text-sm font-semibold">Success</p>
              <p className="text-muted-foreground mt-0.5 text-xs">{toast.message}</p>
              <div className="mt-3 flex items-center gap-2">
                <button
                  onClick={handleDownload}
                  className="bg-primary hover:bg-primary/90 text-primary-foreground inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold transition-all"
                >
                  <FileText className="h-3.5 w-3.5" />
                  Download Report
                </button>
                <button
                  onClick={dismissToast}
                  className="text-muted-foreground hover:text-foreground rounded-lg px-2 py-1.5 text-xs font-medium transition-all"
                >
                  Dismiss
                </button>
              </div>
            </div>
            <button
              onClick={dismissToast}
              className="text-muted-foreground hover:text-foreground -mt-1 -mr-1 rounded-lg p-1 transition-all"
            >
              <span className="text-lg leading-none">&times;</span>
            </button>
          </div>
        </div>
      )}
    </>
  );
};
