-- Recreate official_announcements table if it was dropped by a prior migration
create table if not exists public.official_announcements (
  id bigint primary key generated by default as identity,
  title text not null,
  body text not null,
  category text not null default 'announcement',
  is_pinned boolean default false,
  is_emergency boolean default false,
  department text,
  author_id uuid not null references public.profiles(id) on delete cascade,
  image_url text,
  published_at timestamptz default now(),
  scheduled_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Recreate indexes if they were dropped
create index if not exists idx_official_announcements_author
  on public.official_announcements(author_id);
create index if not exists idx_official_announcements_published
  on public.official_announcements(published_at desc);

-- Re-enable RLS if it was disabled
alter table public.official_announcements enable row level security;

-- Recreate RLS policies (drop existing first to avoid duplicates)
drop policy if exists "Anyone can view official announcements" on public.official_announcements;
drop policy if exists "Officials can insert their own announcements" on public.official_announcements;
drop policy if exists "Officials can update their own announcements" on public.official_announcements;
drop policy if exists "Officials can delete their own announcements" on public.official_announcements;

create policy "Anyone can view official announcements"
  on public.official_announcements for select
  to authenticated
  using (true);

create policy "Officials can insert their own announcements"
  on public.official_announcements for insert
  to authenticated
  with check (author_id = auth.uid());

create policy "Officials can update their own announcements"
  on public.official_announcements for update
  to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

create policy "Officials can delete their own announcements"
  on public.official_announcements for delete
  to authenticated
  using (author_id = auth.uid());

-- Grants for official_announcements table
grant select, insert, update, delete on table public.official_announcements to anon, authenticated;

-- Grants for sequence (required for insert)
grant usage on sequence public.official_announcements_id_seq to anon, authenticated;

-- Recreate RPC functions that may have been dropped by prior migrations

create or replace function public.toggle_announcement_pin(p_announcement_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.official_announcements
  set is_pinned = not is_pinned,
      updated_at = now()
  where id = p_announcement_id
    and author_id = auth.uid();
end;
$$;

create or replace function public.update_announcement_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_announcement_updated_at on public.official_announcements;
create trigger trg_announcement_updated_at
  before update on public.official_announcements
  for each row
  execute function public.update_announcement_timestamp();

-- Grants for RPC functions
grant execute on function public.toggle_announcement_pin to anon, authenticated;
grant execute on function public.update_announcement_timestamp to anon, authenticated;
