-- Add verified badge to profiles
alter table public.profiles
add column if not exists verified boolean default false;

-- Add official announcement columns to community_feed
alter table public.community_feed
add column if not exists is_official boolean default false;

alter table public.community_feed
add column if not exists official_department text;

alter table public.community_feed
add column if not exists is_pinned boolean default false;

alter table public.community_feed
add column if not exists is_emergency boolean default false;

alter table public.community_feed
add column if not exists announcement_category text;

-- Create official_announcements table
create table if not exists public.official_announcements (
  id bigint primary key generated by default as identity,
  title text not null,
  body text not null,
  category text not null default 'announcement',
  is_pinned boolean default false,
  is_emergency boolean default false,
  department text,
  author_id uuid not null references public.profiles(id) on delete cascade,
  image_url text,
  published_at timestamptz default now(),
  scheduled_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Index for listing announcements by author
create index if not exists idx_official_announcements_author
  on public.official_announcements(author_id);

-- Index for listing published announcements
create index if not exists idx_official_announcements_published
  on public.official_announcements(published_at desc);

-- Enable RLS
alter table public.official_announcements enable row level security;

-- RLS: authenticated users can read all official announcements
create policy "Anyone can view official announcements"
  on public.official_announcements for select
  to authenticated
  using (true);

-- RLS: authors can insert their own announcements
create policy "Officials can insert their own announcements"
  on public.official_announcements for insert
  to authenticated
  with check (author_id = auth.uid());

-- RLS: authors can update their own announcements
create policy "Officials can update their own announcements"
  on public.official_announcements for update
  to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

-- RLS: authors can delete their own announcements
create policy "Officials can delete their own announcements"
  on public.official_announcements for delete
  to authenticated
  using (author_id = auth.uid());

-- RPC: search user by email (include verified field)
create or replace function public.search_user_by_email(p_email text)
returns table (
  id uuid,
  email text,
  username text,
  avatar_url text,
  points integer,
  role text,
  verified boolean,
  created_at timestamptz
)
language sql stable
as $$
  select
    au.id,
    au.email::text,
    p.username,
    p.avatar_url,
    p.points,
    p.role,
    p.verified,
    p.created_at
  from auth.users au
  left join public.profiles p on p.id = au.id
  where au.email = p_email
  limit 1;
$$;

-- RPC: update user role (also set verified based on role)
create or replace function public.update_user_role(p_email text, p_role text)
returns void
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
begin
  select id into v_user_id from auth.users where email = p_email;
  if v_user_id is null then
    raise exception 'User not found';
  end if;

  update public.profiles
  set role = p_role,
      verified = (p_role = 'official')
  where id = v_user_id;

  -- Also update auth metadata if needed
  -- (handled by trigger or external process)
end;
$$;

-- RPC: toggle pin status on official announcement
create or replace function public.toggle_announcement_pin(p_announcement_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.official_announcements
  set is_pinned = not is_pinned,
      updated_at = now()
  where id = p_announcement_id
    and author_id = auth.uid();
end;
$$;

-- Trigger: auto-update updated_at
create or replace function public.update_announcement_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_announcement_updated_at
  before update on public.official_announcements
  for each row
  execute function public.update_announcement_timestamp();
