-- Create chatbot knowledge base table
create table public.chatbot_knowledge (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  keywords text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Auto-set updated_at on update
create or replace function public.set_knowledge_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_knowledge_updated_at
  before update on public.chatbot_knowledge
  for each row
  execute function public.set_knowledge_updated_at();

-- RLS
alter table public.chatbot_knowledge enable row level security;

-- Everyone can read
create policy "Anyone can read chatbot knowledge"
  on public.chatbot_knowledge for select
  using (true);

-- Only admins can insert
create policy "Admins can insert chatbot knowledge"
  on public.chatbot_knowledge for insert
  with check (
    auth.role() = 'authenticated'
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Only admins can update
create policy "Admins can update chatbot knowledge"
  on public.chatbot_knowledge for update
  using (
    auth.role() = 'authenticated'
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Only admins can delete
create policy "Admins can delete chatbot knowledge"
  on public.chatbot_knowledge for delete
  using (
    auth.role() = 'authenticated'
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Grant access via Data API
grant usage on sequence public.chatbot_knowledge_id_seq to anon, authenticated;
grant select on table public.chatbot_knowledge to anon, authenticated;
grant insert, update, delete on table public.chatbot_knowledge to authenticated;
grant execute on function public.set_knowledge_updated_at to anon, authenticated;
